[package]
name = "resistance-overwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = { version = "3.4.5", features = ["termination"] }
json = "0.12.4"
log = "0.4.22"
multi_log = "0.1.2"
simplelog = "0.12.2"
syslog = "7.0.0"
